### ISSUE TITLE
 mpd does not report volume when state is stopped 

### ISSUE THREAD

**Issue by MeisterP** [multani/sonata#100]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/sonata/launcher.py", line 198, in on_application_activate
    sonata = main.Base(args)
  File "/usr/lib64/python3.6/site-packages/sonata/main.py", line 767, in __init__
    self.iterate_now()
  File "/usr/lib64/python3.6/site-packages/sonata/main.py", line 1079, in iterate_now
    self.iterate()
  File "/usr/lib64/python3.6/site-packages/sonata/main.py", line 1040, in iterate
    self.handle_change_status()
  File "/usr/lib64/python3.6/site-packages/sonata/main.py", line 1414, in handle_change_status
    self.volumebutton.set_value(int(self.status['volume']))
KeyError: 'volume'
```

a fix for the same issue in mpDris2 is available at https://github.com/eonpatapon/mpDris2/commit/dcf02160d396e838efa752de98663985bcdb6410

**Comment by multani** [comment]
@MeisterP If you are willing to upstream your patch from your overlay, I'd gladly accept it :+1:
