### ISSUE TITLE
Sonata fails to launch

### ISSUE THREAD

**Issue by BobMacpherson** [multani/sonata#104]
Sonata version: 032a34b
MPD version: 0.21.14
OS: Archlinux

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sonata/launcher.py", line 198, in on_application_activate
    sonata = main.Base(args)
  File "/usr/lib/python3.7/site-packages/sonata/main.py", line 767, in __init__
    self.iterate_now()
  File "/usr/lib/python3.7/site-packages/sonata/main.py", line 1079, in iterate_now
    self.iterate()
  File "/usr/lib/python3.7/site-packages/sonata/main.py", line 1040, in iterate
    self.handle_change_status()
  File "/usr/lib/python3.7/site-packages/sonata/main.py", line 1414, in handle_change_status
    self.volumebutton.set_value(int(self.status['volume']))
KeyError: 'volume'

**Comment by hfs** [comment]
This is a duplicate of #100

**Comment by multani** [comment]
See #100 indeed, thanks @hfs
