### ISSUE TITLE
compatible with py 3.9?

### ISSUE THREAD

**Issue by lbazan** [multani/sonata#113]
compatible with py 3.9?

**Comment by multani** [comment]
Let me know!

**Comment by DolphinStKom** [comment]
@multani hi! need fix for python 3.8 and 3.9

`sonata

(sonata:12585): Gtk-WARNING **: 23:08:35.901: Content added to the action area of a dialog using header bars

(sonata:12585): Gtk-WARNING **: 23:08:35.901: Content added to the action area of a dialog using header bars

(sonata:12585): Gtk-WARNING **: 23:08:35.926: Content added to the action area of a dialog using header bars

(sonata:12585): Gtk-WARNING **: 23:08:35.926: Content added to the action area of a dialog using header bars
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sonata/launcher.py", line 201, in on_application_activate
    sonata = main.Base(args)
  File "/usr/lib/python3.8/site-packages/sonata/main.py", line 767, in __init__
    self.iterate_now()
  File "/usr/lib/python3.8/site-packages/sonata/main.py", line 1079, in iterate_now
    self.iterate()
  File "/usr/lib/python3.8/site-packages/sonata/main.py", line 1040, in iterate
    self.handle_change_status()
  File "/usr/lib/python3.8/site-packages/sonata/main.py", line 1359, in handle_change_status
    self.current.current_update(prevstatus_playlist,
  File "/usr/lib/python3.8/site-packages/sonata/current.py", line 128, in do_try_keep_position
    result = func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sonata/current.py", line 245, in current_update
    changed_songs = self.mpd.plchanges(0)
  File "/usr/lib/python3.8/site-packages/sonata/mpdhelper.py", line 55, in _call
    retval = cmd(*args)
  File "/usr/lib/python3.8/site-packages/mpd/base.py", line 389, in mpd_command
    return wrapper(self, name, args, callback)
  File "/usr/lib/python3.8/site-packages/mpd/base.py", line 482, in _execute
    return retval()
  File "/usr/lib/python3.8/site-packages/mpd/base.py", line 379, in command_callback
    res = self._wrap_iterator(res)
  File "/usr/lib/python3.8/site-packages/mpd/base.py", line 569, in _wrap_iterator
    return list(iterator)
  File "/usr/lib/python3.8/site-packages/mpd/base.py", line 225, in _parse_objects
    for key, value in self._parse_pairs(lines):
  File "/usr/lib/python3.8/site-packages/mpd/base.py", line 220, in _parse_pairs
    for line in lines:
  File "/usr/lib/python3.8/site-packages/mpd/base.py", line 547, in _read_lines
    line = self._read_line()
  File "/usr/lib/python3.8/site-packages/mpd/base.py", line 527, in _read_line
    line = self._rfile.readline()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
`

**Comment by multani** [comment]
@DolphinStKom Looks like an issue with your version of python-mpd2, not Sonata. AFAIK, it works fine with both Python 3.8 and Python 3.9.
