### ISSUE TITLE
Window not shown with lyricsfetcher error

### ISSUE THREAD

**Issue by PeterNerlich** [multani/sonata#114]
Apparently there is an error when looking for lyrics, which prevents the app window from showing. When running from terminal I get these messages:

    $ sonata --version
    sonata 1.7a2-100-gcee35
    $ sonata -v
    
    (sonata:6553): Gtk-WARNING **: 11:43:19.705: Content added to the action area of a dialog using header bars
    
    (sonata:6553): Gtk-WARNING **: 11:43:19.705: Content added to the action area of a dialog using header bars
    
    (sonata:6553): Gtk-WARNING **: 11:43:19.750: Content added to the action area of a dialog using header bars
    
    (sonata:6553): Gtk-WARNING **: 11:43:19.750: Content added to the action area of a dialog using header bars
    
    (sonata:6553): Gtk-CRITICAL **: 11:43:19.795: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
    [2020-08-19 11:43:19] [LyricsFetcher] sonata.info: Looking for lyrics for 'Disasterpeace' - 'Home'...
    
    (sonata:6553): Gtk-CRITICAL **: 11:43:19.804: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
    [2020-08-19 11:43:19] [LyricsFetcher] sonata.plugins.lyricwiki: Downloading lyrics from 'http://lyrics.wikia.com/index.php?title=Disasterpeace:Home&action=edit'
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/sonata/launcher.py", line 198, in on_application_activate
        sonata = main.Base(args)
      File "/usr/lib/python3.8/site-packages/sonata/main.py", line 767, in __init__
        self.iterate_now()
      File "/usr/lib/python3.8/site-packages/sonata/main.py", line 1079, in iterate_now
        self.iterate()
      File "/usr/lib/python3.8/site-packages/sonata/main.py", line 1040, in iterate
        self.handle_change_status()
      File "/usr/lib/python3.8/site-packages/sonata/main.py", line 1425, in handle_change_status
        self.mpd_updated_db()
      File "/usr/lib/python3.8/site-packages/sonata/main.py", line 1463, in mpd_updated_db
        self.library.library_browse(root=self.config.wd)
      File "/usr/lib/python3.8/site-packages/sonata/library.py", line 387, in library_browse
        bd = self.library_populate_toplevel_data(artistview=True)
      File "/usr/lib/python3.8/site-packages/sonata/library.py", line 585, in library_populate_toplevel_data
        items = self.library_return_list_items('artist')
      File "/usr/lib/python3.8/site-packages/sonata/library.py", line 795, in library_return_list_items
        results.sort(key=locale.strxfrm)
    TypeError: strxfrm() argument 1 must be str, not dict
    [2020-08-19 11:43:20] [LyricsFetcher] sonata.info: Plugin lyricwiki: unable to fetch lyrics (list index out of range)

Then it hangs indefinitely.

While this error should also be fixed, I expect the program to work normally, minus the lyrics functionality, if such an error occours.

**Comment by multani** [comment]
Hi @PeterNerlich!

Can you try to update your version of Sonata? I think you are seeing 2 errors here:

* the main one is the `strxfrm()` error, which I believe was fixed in c4b91635696b6754c4d872e71273101fdd720cb1
* the lyrics fetching error, but I think this one is unrelated to your crash, I'll try to have a look.

**Comment by PeterNerlich** [comment]
Ah yes, all perfect!

When updating I just noticed that I had actually the git one installed from the AUR, so I guess I was simply inbetween versions before and wouldn't get prompted to upgrade automatically until the next version bump...? ...is what I would now expect...

Thank you very much! Btw. I'm now running version:

    $ sonata --version
    sonata 1.7a2-107-g0c80
