### ISSUE TITLE
UnicodeEncodeError after updating mpd: ascii codec can't encode \xe4

### ISSUE THREAD

**Issue by carstenhag** [multani/sonata#72]
Today I ran mpd, ncmpcpp and sonata and everything worked fine. Then, after running pacman -Syu and it updating mpd, I tried to start sonata again. I'm now getting this error. I haven't run pacman -Syu for some weeks.

```
carstenh@arch-moteer8 ~> sonata
(sonata:8600): Gtk-WARNING **: Content added to the action area of a dialog using header bars
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sonata/launcher.py", line 191, in on_application_activate
    sonata = main.Base(args)
  File "/usr/lib/python3.4/site-packages/sonata/main.py", line 759, in __init__
    self.iterate_now()
  File "/usr/lib/python3.4/site-packages/sonata/main.py", line 1065, in iterate_now
    self.iterate()
  File "/usr/lib/python3.4/site-packages/sonata/main.py", line 1026, in iterate
    self.handle_change_status()
  File "/usr/lib/python3.4/site-packages/sonata/main.py", line 1367, in handle_change_status
    self.info_update(True)
  File "/usr/lib/python3.4/site-packages/sonata/main.py", line 1169, in info_update
    update_all)
  File "/usr/lib/python3.4/site-packages/sonata/info.py", line 261, in update
    getattr(self, "_update_%s" % func)(songinfo)
  File "/usr/lib/python3.4/site-packages/sonata/info.py", line 278, in _update_song
    if os.path.exists(path):
  File "/usr/lib/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 52: ordinal not in range(128)
```

[mpd.conf](https://gist.github.com/Moter8/35775f7ff7c00ff25fc5)

```
mpd 0.19.8-1
sonata-git v1.7a2.r62.gace5e33-1
Kernel: Linux 3.17.6-1-ARCH x86_64
```

**Comment by Moter8** [comment]
Hey, some nice user on #archlinux helped me fix this by executing `env LANG='de_DE.utf8' sonata`.

`locale -a`showed that my `LANG` wasn't set at all (because I'm using fish-shell etc...)

Not sure why this didn't happen before though, but it seems solved now as sonata starts again.

**Comment by multani** [comment]
OK cool!
I'll this open though, to see if there's no weird thing lying around that I missed in the last patch.
